# Launch Daily Loop

In [1]:
import os, sys, random, json, datetime, statistics
import pandas as PD

In [2]:
BACKEND_PATH = os.path.dirname(os.path.dirname(os.getcwd()))
APPPROJ_PATH = os.path.join(BACKEND_PATH, 'app_proj')
sys.path.append(APPPROJ_PATH)
import notebooks as NT
print([x for x in dir(NT) if x[0]!='_' and len(x)>8])

['DataframeToDicts', 'GetRandom', 'NOTEBOOK_ENV']

In [3]:
import django
os.environ['DEPLOYMENT_ENV'] = NT.NOTEBOOK_ENV
os.environ['DJANGO_ALLOW_ASYNC_UNSAFE'] = 'True'
MODULE_PATH = os.path.dirname(os.getcwd())
os.chdir(os.path.dirname(MODULE_PATH))
django.setup()

env: DEV

In [4]:
from django.utils import timezone

In [5]:
import database as DB
print([x for x in dir(DB) if x[0]!='_' and len(x)>8])

['BaseManager', 'DeleteTable', 'GetNativeTableCounts', 'GetTableCounts', 'GetTableDictionary', 'InsertBulk', 'InsertSingle']

In [6]:
import django.db.models as JM
from django.contrib.auth import get_user_model

In [7]:
import emporium.models as EM

import engine.models as GM
import engine.logic.content as CT
import engine.logic.launcher as LC
import engine.logic.simulation as SM

In [8]:
%load_ext autoreload
%autoreload 2
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
import IPython.display as DS 
from ipywidgets import IntProgress

### Guild Properties

In [9]:
userMd = get_user_model().objects.filter(user_name='Admin')[0]
userMd

In [10]:
guild = GM.Guild.objects.GetOrNone(UserFK=userMd, Name='123')
PD.DataFrame([guild.__dict__]).drop(['id', '_state'], axis=1, errors='ignore')

,UserFK_id,Name,KeepLevel,TotalPower,VaultGold,VaultGems,Selected,LastPlayed,CreateDate
0,1,123,1,0,0,0,True,2023-08-12,2023-08-12

In [11]:
thieves = GM.ThiefInGuild.objects.filter(GuildFK=guild).values()
PD.DataFrame(thieves).drop(['id',
        'Name', 'BasePower', 'Experience', 
        'Position', 
        'BaseAgi', 'BaseCun', 'BaseMig', 'BaseEnd', 
        'TrainedAgi', 'TrainedCun', 'TrainedMig', 'TrainedEnd', 
        'Sabotage', 'Perceive', 'Traverse',
        ], axis=1, errors='ignore')

,GuildFK_id,Class,Stars,Level,Power,Agility,Cunning,Might,Endurance,Health,Attack,Damage,Defense,Wounds,Cooldown
0,20,Burglar,1,1,60,5,0,0,0,70,5,11,13,None,None
1,20,Scoundrel,1,1,60,0,5,0,0,70,2,15,12,None,None
2,20,Ruffian,1,1,60,0,0,5,0,70,3,10,16,None,None
3,20,Burglar,1,1,60,5,0,0,0,70,5,11,13,None,None

In [12]:
CT.SetTestRamp(guild)

In [13]:
rampStages = GM.GuildRamp.objects.all().values()
PD.DataFrame(rampStages).drop(['id'], axis=1, errors='ignore')

,GuildFK_id,StageNo,StageDate,ObstaclesR1,TypeR1,CompleteR1
0,20,1,2023-08-12,"[{""Level"": 2, ""Name"": ""Secret Passage"", ""Trait...",balanced,False
1,20,2,2023-08-12,"[{""Level"": 2, ""Name"": ""Window"", ""Trait"": ""Mig""...",biased agi,False
2,20,3,2023-08-12,"[{""Level"": 2, ""Name"": ""Vanguard"", ""Trait"": ""An...",balanced,False
3,20,4,2023-08-12,"[{""Level"": 2, ""Name"": ""Chandelier"", ""Trait"": ""...",biased mig,False
4,20,5,2023-08-12,"[{""Level"": 2, ""Name"": ""Sorcerer"", ""Trait"": ""An...",balanced,False
5,20,6,2023-08-12,"[{""Level"": 2, ""Name"": ""Arcane Seal"", ""Trait"": ...",balanced,False
6,20,7,2023-08-12,"[{""Level"": 2, ""Name"": ""Sorcerer"", ""Trait"": ""An...",balanced,False
7,20,8,2023-08-12,"[{""Level"": 2, ""Name"": ""Door"", ""Trait"": ""Agi"", ...",balanced,False
8,20,9,2023-08-12,"[{""Level"": 2, ""Name"": ""Gargoyle"", ""Trait"": ""Mi...",biased agi,False
9,20,10,2023-08-12,"[{""Level"": 2, ""Name"": ""Barrel"", ""Trait"": ""Mig""...",balanced,False
10,20,11,2023-08-12,"[{""Level"": 2, ""Name"": ""Barrel"", ""Trait"": ""Mig""...",biased mig,False
11,20,12,2023-08-12,"[{""Level"": 2, ""Name"": ""Crossbow Trap"", ""Trait""...",balanced,False
12,20,13,2023-08-12,"[{""Level"": 2, ""Name"": ""Sorcerer"", ""Trait"": ""An...",balanced,False
13,20,14,2023-08-12,"[{""Level"": 2, ""Name"": ""Barrel"", ""Trait"": ""Mig""...",balanced,False
14,20,15,2023-08-12,"[{""Level"": 2, ""Name"": ""Sorcerer"", ""Trait"": ""An...",biased cun,False
15,20,16,2023-08-12,"[{""Level"": 2, ""Name"": ""Warden"", ""Trait"": ""Any""...",balanced,False
16,20,17,2023-08-12,"[{""Level"": 2, ""Name"": ""Sorcerer"", ""Trait"": ""An...",balanced,False
17,20,18,2023-08-12,"[{""Level"": 2, ""Name"": ""Door"", ""Trait"": ""Agi"", ...",biased agi,False
18,20,19,2023-08-12,"[{""Level"": 2, ""Name"": ""Spike Trap"", ""Trait"": ""...",balanced,False
19,20,20,2023-08-12,"[{""Level"": 2, ""Name"": ""Barrel"", ""Trait"": ""Mig""...",balanced,False
20,20,21,2023-08-12,"[{""Level"": 2, ""Name"": ""Secret Passage"", ""Trait...",biased mig,False
21,20,22,2023-08-12,"[{""Level"": 2, ""Name"": ""Sorcerer"", ""Trait"": ""An...",balanced,False
22,20,23,2023-08-12,"[{""Level"": 2, ""Name"": ""Arcane Seal"", ""Trait"": ...",biased cun,False
23,20,24,2023-08-12,"[{""Level"": 2, ""Name"": ""Window"", ""Trait"": ""Mig""...",balanced,False
24,20,25,2023-08-12,"[{""Level"": 2, ""Name"": ""Chandelier"", ""Trait"": ""...",biased cun,False
25,20,26,2023-08-12,"[{""Level"": 2, ""Name"": ""Spike Trap"", ""Trait"": ""...",balanced,False
26,20,27,2023-08-12,"[{""Level"": 2, ""Name"": ""Vanguard"", ""Trait"": ""An...",balanced,False
27,20,28,2023-08-12,"[{""Level"": 2, ""Name"": ""Crossbow Trap"", ""Trait""...",biased cun,False

### Robot Loop

In [14]:
# prepare daily content

SM.ResetCooldowns(guild)

SM.RefreshEquipment(guild)

CT.SetTestRamp(guild)

# run test ramp

stopLoop = 0
while True and stopLoop < 10:

    print('-------------')
    
    # get thief assignments

    nextStage = SM.GetNextRamp(guild)
    PD.DataFrame([nextStage.__dict__]).drop(['id', '_state', 'GuildFK_id'], axis=1, errors='ignore')

    thieves = list(GM.ThiefInGuild.objects.filter(GuildFK=guild).order_by('Power'))
    readyLs = [x for x in thieves if x.Cooldown is None]

    stagePlays = SM.GetRampAssignments(readyLs, nextStage)
    if not stagePlays: break

    # launch current stage
    
    res1, res2, res3 = LC.LaunchStage(stagePlays, nextStage)
    PD.DataFrame(res1)

    # record results
    
    rollParams = [x['rollParams'] for x in res1]
    stagePlays[0]['obstacleResults'] = rollParams
    stagePlays[0]['wounds'] = stagePlays[0]['thief'].Wounds
    
    if stagePlays[0]['thief'].Wounds >= stagePlays[0]['thief'].Health /2:
        stagePlays[0]['thief'].Cooldown = timezone.now() + datetime.timedelta(hours=1)
        stagePlays[0]['thief'].save()

    nextStage.CompleteR1 = len(json.loads(nextStage.ObstaclesR1)) == res1[-1]['nextPos']
    nextStage.save()

    PD.DataFrame(stagePlays)

    stopLoop += 1

-------------

,StageNo,StageDate,ObstaclesR1,TypeR1,CompleteR1
0,1,2023-08-12,"[{""Level"": 2, ""Name"": ""Warden"", ""Trait"": ""Any""...",balanced,False

,obstacle,currPos,nextPos,rollParams,reward,wounds
0,Warden,0,1,"[{'attacker': 'thief', 'roll': 4, 'attack': 5,...",xp 13,11.0
1,Spike Trap,1,2,"{'roll': 13, 'traitBonus': 5, 'skillBonus': 0,...",xp 8,NaN
2,Vanguard,2,3,"[{'attacker': 'thief', 'roll': 18, 'attack': 5...",xp 13,8.0
3,Barrel,3,4,"{'roll': 11, 'traitBonus': 0, 'skillBonus': 0,...",None,9.0
4,Spike Trap,4,5,"{'roll': 7, 'traitBonus': 5, 'skillBonus': 0, ...",None,12.0
5,Sorcerer,5,5,"[{'attacker': 'thief', 'roll': 4, 'attack': 5,...",None,31.0

,thief,room,obstacleResults,roomResults,wounds
0,Burglar 60 1,1,"[[{'attacker': 'thief', 'roll': 4, 'attack': 5...",{},71

-------------

,StageNo,StageDate,ObstaclesR1,TypeR1,CompleteR1
0,1,2023-08-12,"[{""Level"": 2, ""Name"": ""Warden"", ""Trait"": ""Any""...",balanced,False

,obstacle,currPos,nextPos,rollParams,reward,wounds
0,Warden,0,1,"[{'attacker': 'thief', 'roll': 19, 'attack': 5...",xp 13,7.0
1,Spike Trap,1,2,"{'roll': 12, 'traitBonus': 5, 'skillBonus': 0,...",xp 8,NaN
2,Vanguard,2,3,"[{'attacker': 'thief', 'roll': 8, 'attack': 5,...",xp 13,0.0
3,Barrel,3,4,"{'roll': 4, 'traitBonus': 0, 'skillBonus': 0, ...",None,18.0
4,Spike Trap,4,5,"{'roll': 14, 'traitBonus': 5, 'skillBonus': 0,...",xp 8,NaN
5,Sorcerer,5,6,"[{'attacker': 'thief', 'roll': 20, 'attack': 5...",xp 13,0.0

,thief,room,obstacleResults,roomResults,wounds
0,Burglar 70 1,1,"[[{'attacker': 'thief', 'roll': 19, 'attack': ...",{},25

-------------

,StageNo,StageDate,ObstaclesR1,TypeR1,CompleteR1
0,2,2023-08-12,"[{""Level"": 2, ""Name"": ""Secret Passage"", ""Trait...",balanced,False

,obstacle,currPos,nextPos,rollParams,reward,wounds
0,Secret Passage,0,2,"{'roll': 16, 'traitBonus': 0, 'skillBonus': 5,...",xp 8,NaN
1,Door,2,3,"{'roll': 17, 'traitBonus': 5, 'skillBonus': 0,...",xp 8,NaN
2,Idol,3,4,"{'roll': 15, 'traitBonus': 0, 'skillBonus': 5,...",gold 1,NaN
3,Vanguard,4,5,"[{'attacker': 'thief', 'roll': 13, 'attack': 5...",xp 13,0.0
4,Idol,5,6,"{'roll': 7, 'traitBonus': 0, 'skillBonus': 5, ...",None,NaN
5,Warden,6,7,"[{'attacker': 'thief', 'roll': 17, 'attack': 5...",xp 13,4.0

,thief,room,obstacleResults,roomResults,wounds
0,Burglar 70 1,1,"[{'roll': 16, 'traitBonus': 0, 'skillBonus': 5...",{},4

-------------

,StageNo,StageDate,ObstaclesR1,TypeR1,CompleteR1
0,3,2023-08-12,"[{""Level"": 2, ""Name"": ""Arcane Seal"", ""Trait"": ...",biased agi,False

,obstacle,currPos,nextPos,rollParams,reward,wounds
0,Arcane Seal,0,1,"{'roll': 12, 'traitBonus': 0, 'skillBonus': 0,...",None,6.0
1,Sorcerer,1,2,"[{'attacker': 'thief', 'roll': 18, 'attack': 5...",xp 13,0.0
2,Window,2,3,"{'roll': 12, 'traitBonus': 0, 'skillBonus': 0,...",None,11.0
3,Gargoyle,3,4,"{'roll': 12, 'traitBonus': 0, 'skillBonus': 0,...",None,13.0
4,Chest,4,5,"{'roll': 6, 'traitBonus': 5, 'skillBonus': 0, ...",None,NaN
5,Door,5,6,"{'roll': 1, 'traitBonus': 5, 'skillBonus': 0, ...",None,10.0
6,Armoire,6,7,"{'roll': 4, 'traitBonus': 0, 'skillBonus': 0, ...",None,NaN
7,Warden,7,8,"[{'attacker': 'thief', 'roll': 16, 'attack': 5...",xp 13,10.0

,thief,room,obstacleResults,roomResults,wounds
0,Burglar 70 1,1,"[{'roll': 12, 'traitBonus': 0, 'skillBonus': 0...",{},50

-------------

,StageNo,StageDate,ObstaclesR1,TypeR1,CompleteR1
0,4,2023-08-12,"[{""Level"": 2, ""Name"": ""Warden"", ""Trait"": ""Any""...",balanced,False

,obstacle,currPos,nextPos,rollParams,reward,wounds
0,Warden,0,1,"[{'attacker': 'thief', 'roll': 15, 'attack': 2...",xp 13,0.0
1,Idol,1,2,"{'roll': 18, 'traitBonus': 0, 'skillBonus': 0,...",gold 1,NaN
2,Door,2,3,"{'roll': 13, 'traitBonus': 0, 'skillBonus': 5,...",xp 8,NaN
3,Barrel,3,4,"{'roll': 15, 'traitBonus': 0, 'skillBonus': 0,...",xp 8,NaN
4,Chandelier,4,6,"{'roll': 19, 'traitBonus': 0, 'skillBonus': 0,...",xp 8,NaN
5,Crossbow Trap,6,7,"{'roll': 10, 'traitBonus': 5, 'skillBonus': 0,...",xp 8,NaN
6,Sorcerer,7,8,"[{'attacker': 'thief', 'roll': 5, 'attack': 2,...",xp 13,12.0
7,Barrel,8,9,"{'roll': 18, 'traitBonus': 0, 'skillBonus': 0,...",xp 8,NaN

,thief,room,obstacleResults,roomResults,wounds
0,Scoundrel 70 1,1,"[[{'attacker': 'thief', 'roll': 15, 'attack': ...",{},12

-------------

,StageNo,StageDate,ObstaclesR1,TypeR1,CompleteR1
0,5,2023-08-12,"[{""Level"": 2, ""Name"": ""Vanguard"", ""Trait"": ""An...",balanced,False

,obstacle,currPos,nextPos,rollParams,reward,wounds
0,Vanguard,0,1,"[{'attacker': 'thief', 'roll': 11, 'attack': 2...",xp 13,0
1,Chandelier,1,2,"{'roll': 2, 'traitBonus': 0, 'skillBonus': 0, ...",None,12
2,Sorcerer,2,3,"[{'attacker': 'thief', 'roll': 1, 'attack': 2,...",xp 13,56
3,Arcane Seal,3,3,"{'roll': 1, 'traitBonus': 5, 'skillBonus': 5, ...",None,9

,thief,room,obstacleResults,roomResults,wounds
0,Scoundrel 70 1,1,"[[{'attacker': 'thief', 'roll': 11, 'attack': ...",{},77

-------------

,StageNo,StageDate,ObstaclesR1,TypeR1,CompleteR1
0,5,2023-08-12,"[{""Level"": 2, ""Name"": ""Vanguard"", ""Trait"": ""An...",balanced,False

,obstacle,currPos,nextPos,rollParams,reward,wounds
0,Vanguard,0,1,"[{'attacker': 'thief', 'roll': 8, 'attack': 3,...",xp 13,10.0
1,Chandelier,1,2,"{'roll': 6, 'traitBonus': 0, 'skillBonus': 0, ...",None,11.0
2,Sorcerer,2,3,"[{'attacker': 'thief', 'roll': 2, 'attack': 3,...",xp 13,0.0
3,Arcane Seal,3,4,"{'roll': 8, 'traitBonus': 0, 'skillBonus': 0, ...",None,18.0
4,Chest,4,5,"{'roll': 6, 'traitBonus': 0, 'skillBonus': 0, ...",None,NaN
5,Crossbow Trap,5,6,"{'roll': 14, 'traitBonus': 0, 'skillBonus': 0,...",xp 8,NaN
6,Warden,6,7,"[{'attacker': 'thief', 'roll': 16, 'attack': 3...",xp 13,23.0
7,Crossbow Trap,7,7,"{'roll': 2, 'traitBonus': 0, 'skillBonus': 0, ...",None,16.0

,thief,room,obstacleResults,roomResults,wounds
0,Ruffian 70 1,1,"[[{'attacker': 'thief', 'roll': 8, 'attack': 3...",{},78

-------------

,StageNo,StageDate,ObstaclesR1,TypeR1,CompleteR1
0,5,2023-08-12,"[{""Level"": 2, ""Name"": ""Vanguard"", ""Trait"": ""An...",balanced,False

In [15]:
thieves = GM.ThiefInGuild.objects.filter(GuildFK=guild).values()
PD.DataFrame(thieves).drop(['id',
        'Name', 'BasePower', 'Experience', 
        'Position', 
        'BaseAgi', 'BaseCun', 'BaseMig', 'BaseEnd', 
        'TrainedAgi', 'TrainedCun', 'TrainedMig', 'TrainedEnd', 
        'Sabotage', 'Perceive', 'Traverse',
        ], axis=1, errors='ignore')

,GuildFK_id,Class,Stars,Level,Power,Agility,Cunning,Might,Endurance,Health,Attack,Damage,Defense,Wounds,Cooldown
0,20,Burglar,1,1,70,5,0,0,0,70,5,11,13,50,2023-08-12 22:53:05.661626+00:00
1,20,Scoundrel,1,1,70,0,5,0,0,70,2,15,12,77,2023-08-12 22:53:05.739764+00:00
2,20,Ruffian,1,1,70,0,0,5,0,70,3,10,16,78,2023-08-12 22:53:05.793148+00:00
3,20,Burglar,1,1,60,5,0,0,0,70,5,11,13,71,2023-08-12 22:53:05.523612+00:00

### Statistical Simulation

In [16]:
SM.RefreshEquipment(guild)

In [17]:
def RunDailyRamp():
    
    # prepare daily content

    SM.ResetCooldowns(guild)

    CT.SetTestRamp(guild)

    # run test ramp

    while True:

        # get thief assignments

        nextStage = SM.GetNextRamp(guild)

        thieves = list(GM.ThiefInGuild.objects.filter(GuildFK=guild).order_by('Power'))
        readyLs = [x for x in thieves if x.Cooldown is None]

        stagePlays = SM.GetRampAssignments(readyLs, nextStage)
        if not stagePlays: break

        # launch current stage

        res1, res2, res3 = LC.LaunchStage(stagePlays, nextStage)

        # record results

        rollParams = [x['rollParams'] for x in res1]
        stagePlays[0]['obstacleResults'] = rollParams
        stagePlays[0]['wounds'] = stagePlays[0]['thief'].Wounds

        if stagePlays[0]['thief'].Wounds >= stagePlays[0]['thief'].Health /2:
            stagePlays[0]['thief'].Cooldown = timezone.now() + datetime.timedelta(hours=1)
            stagePlays[0]['thief'].save()

        nextStage.CompleteR1 = len(json.loads(nextStage.ObstaclesR1)) == res1[-1]['nextPos']
        nextStage.save()

    return nextStage.StageNo

In [18]:
TRIALS = 300
results = []
progressBar = IntProgress(min=0, max=TRIALS) 
DS.display(progressBar) 

for tr in range(0, TRIALS):
    results.append(RunDailyRamp())
    progressBar.value += 1

round(statistics.mean(results), 1)

IntProgress(value=0, max=300)

5.5